##individual
post_i <- extract(fit_i)
str(post_i)
precis(fit_i)
precis(fit_i , pars='lambda_i' , depth=2)
precis(fit_i , pars='phi_i' , depth=2)
DensLambda(post_i)
DensPhi(post_i)

traceplot(fit_i , pars='sigma_i')
traceplot(fit_i , pars='lambda')
traceplot(fit_i , pars='phi')

##freq dep
post_freq <- extract(fit_freq)
str(post_freq)
precis(fit_freq)
precis(fit_freq , pars='lambda_i' , depth=2)
precis(fit_freq , pars='phi_i' , depth=2)
precis(fit_freq , pars='gamma_i' , depth=2)
precis(fit_freq , pars='fc_i' , depth=2)
DensLambda(post_freq)
DensPhi(post_freq)
DensGamma(post_freq)
DensFc(post_freq)
traceplot(fit_freq , pars='sigma_i')
traceplot(fit_freq , pars='lambda')
traceplot(fit_freq , pars='phi')
traceplot(fit_freq , pars='gamma')
traceplot(fit_freq , pars='fc')

##male-bias
post_male <- extract(fit_male)
str(post_male)
precis(fit_male)
precis(fit_male , pars='lambda_i' , depth=2)
precis(fit_male , pars='phi_i' , depth=2)
precis(fit_male , pars='gamma_i' , depth=2)
precis(fit_male , pars='betaq_i' , depth=2)
DensLambda(post_male)
DensPhi(post_male)
DensGamma(post_male)
DensBetaq(post_male)
traceplot(fit_male , pars='sigma_i')
traceplot(fit_male , pars='lambda')
traceplot(fit_male , pars='phi')
traceplot(fit_male , pars='gamma')
traceplot(fit_male , pars='betaq')
