
pdf(file = "param_posteriors.pdf" , width = 8, height = 8) # The height of the plot in inches
par(mfrow=c(5,5) , mar=c(2,.1,.1,.1) + 0.1 , oma=c(0,0,1,0) +1 )
DensLambda(post_freq , unknown=FALSE )
mtext("lambda" , line=.25 , side=3 , cex=0.7)
mtext("frequency-dependence" , line=.25 , side=2 , cex=0.7)
DensPhi(post_freq , unknown=FALSE )
mtext("phi" , line=.25 , side=3 , cex=0.7)
DensGamma(post_freq , unknown=FALSE)
mtext("gamma" , line=.25 , side=3 , cex=0.7)
DensFc(post_freq , unknown=FALSE)
mtext("f" , line=.25 , side=3 , cex=0.7)
plot.new()
mtext("beta" , line=.25 , side=3 , cex=0.7)
DensLambda(post_male_lin , unknown=FALSE )
mtext("male-bias" , line=.25 , side=2 , cex=0.7)
DensPhi(post_male_lin , unknown=FALSE )
DensGamma(post_male_lin , unknown=FALSE)
plot.new()
plot.new()
DensLambda(post_adult_lin , unknown=FALSE )
mtext("adult-bias" , line=.25 , side=2 , cex=0.7)
DensPhi(post_adult_lin , unknown=FALSE )
DensGamma(post_adult_lin , unknown=FALSE)
plot.new()
plot.new()
DensLambda(post_roost , unknown=FALSE )
mtext("same-roost-bias" , line=.25 , side=2 , cex=0.7)
DensPhi(post_roost , unknown=FALSE )
DensGamma(post_roost , unknown=FALSE)
plot.new()
DensBetaq(post_roost, unknown=FALSE )
DensLambda(post_ind , unknown=FALSE )
mtext("individual learning" , line=.25 , side=2 , cex=0.7)
DensPhi(post_ind , unknown=FALSE )
plot.new()
plot.new()
dev.off()